# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventConfigurationOpen.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 351)
        Dialog.setMinimumSize(QtCore.QSize(618, 300))
        Dialog.setMaximumSize(QtCore.QSize(618, 351))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ec_frame = QtWidgets.QFrame(Dialog)
        self.ec_frame.setMinimumSize(QtCore.QSize(600, 300))
        self.ec_frame.setMaximumSize(QtCore.QSize(725, 300))
        self.ec_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ec_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ec_frame.setObjectName("ec_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ec_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_event_name = QtWidgets.QLabel(self.ec_frame)
        self.label_event_name.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_event_name.setObjectName("label_event_name")
        self.verticalLayout_4.addWidget(self.label_event_name)
        self.comboBox = QtWidgets.QComboBox(self.ec_frame)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_4.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_event_start = QtWidgets.QLabel(self.ec_frame)
        self.label_event_start.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_event_start.setObjectName("label_event_start")
        self.verticalLayout_5.addWidget(self.label_event_start)
        self.label = QtWidgets.QLabel(self.ec_frame)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_event_end = QtWidgets.QLabel(self.ec_frame)
        self.label_event_end.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_event_end.setObjectName("label_event_end")
        self.verticalLayout_6.addWidget(self.label_event_end)
        self.label_2 = QtWidgets.QLabel(self.ec_frame)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.ec_label = QtWidgets.QLabel(self.ec_frame)
        self.ec_label.setMaximumSize(QtCore.QSize(16777215, 28))
        self.ec_label.setObjectName("ec_label")
        self.gridLayout_3.addWidget(self.ec_label, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_event_description = QtWidgets.QLabel(self.ec_frame)
        self.label_event_description.setObjectName("label_event_description")
        self.verticalLayout_7.addWidget(self.label_event_description)
        self.label_3 = QtWidgets.QLabel(self.ec_frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.ec_frame, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_event_name.setText(_translate("Dialog", "Event Name"))
        self.label_event_start.setText(_translate("Dialog", "Event Start"))
        self.label_event_end.setText(_translate("Dialog", "Event End"))
        self.ec_label.setText(_translate("Dialog", "Event Configuration - Open Event"))
        self.label_event_description.setText(_translate("Dialog", "Description"))
        self.label_3.setText(_translate("Dialog", "Event description goes here."))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
