# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icon_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_icon_configuration(object):
    def setupUi(self, icon_configuration):
        icon_configuration.setObjectName("icon_configuration")
        icon_configuration.resize(637, 548)
        self.icon_centralwidget = QtWidgets.QWidget(icon_configuration)
        self.icon_centralwidget.setObjectName("icon_centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon_configBox = QtWidgets.QGroupBox(self.icon_centralwidget)
        self.icon_configBox.setMinimumSize(QtCore.QSize(351, 70))
        self.icon_configBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.icon_configBox.setAutoFillBackground(True)
        self.icon_configBox.setObjectName("icon_configBox")
        self.icon_addIcon = QtWidgets.QPushButton(self.icon_configBox)
        self.icon_addIcon.setGeometry(QtCore.QRect(20, 30, 89, 25))
        self.icon_addIcon.setObjectName("icon_addIcon")
        self.icon_deleteIcon = QtWidgets.QPushButton(self.icon_configBox)
        self.icon_deleteIcon.setGeometry(QtCore.QRect(130, 30, 89, 25))
        self.icon_deleteIcon.setObjectName("icon_deleteIcon")
        self.icon_editIcon = QtWidgets.QPushButton(self.icon_configBox)
        self.icon_editIcon.setGeometry(QtCore.QRect(240, 30, 89, 25))
        self.icon_editIcon.setObjectName("icon_editIcon")
        self.verticalLayout.addWidget(self.icon_configBox)
        self.IconTable = QtWidgets.QTableWidget(self.icon_centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IconTable.sizePolicy().hasHeightForWidth())
        self.IconTable.setSizePolicy(sizePolicy)
        self.IconTable.setMinimumSize(QtCore.QSize(500, 300))
        self.IconTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.IconTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.IconTable.setAutoFillBackground(True)
        self.IconTable.setObjectName("IconTable")
        self.IconTable.setColumnCount(4)
        self.IconTable.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.IconTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.IconTable.setItem(5, 3, item)
        self.IconTable.horizontalHeader().setCascadingSectionResizes(True)
        self.IconTable.horizontalHeader().setDefaultSectionSize(130)
        self.IconTable.horizontalHeader().setMinimumSectionSize(130)
        self.IconTable.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout.addWidget(self.IconTable)
        icon_configuration.setCentralWidget(self.icon_centralwidget)
        self.menubar = QtWidgets.QMenuBar(icon_configuration)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 22))
        self.menubar.setObjectName("menubar")
        icon_configuration.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(icon_configuration)
        self.statusbar.setObjectName("statusbar")
        icon_configuration.setStatusBar(self.statusbar)

        self.retranslateUi(icon_configuration)
        QtCore.QMetaObject.connectSlotsByName(icon_configuration)

    def retranslateUi(self, icon_configuration):
        _translate = QtCore.QCoreApplication.translate
        icon_configuration.setWindowTitle(_translate("icon_configuration", "MainWindow"))
        self.icon_configBox.setTitle(_translate("icon_configuration", "Icon Configuration"))
        self.icon_addIcon.setText(_translate("icon_configuration", "Add Icon"))
        self.icon_deleteIcon.setText(_translate("icon_configuration", "Delete Icon"))
        self.icon_editIcon.setText(_translate("icon_configuration", "Edit Icon"))
        item = self.IconTable.horizontalHeaderItem(1)
        item.setText(_translate("icon_configuration", "Icon Name"))
        item = self.IconTable.horizontalHeaderItem(2)
        item.setText(_translate("icon_configuration", "Icon Source"))
        item = self.IconTable.horizontalHeaderItem(3)
        item.setText(_translate("icon_configuration", "Image Preview"))
        __sortingEnabled = self.IconTable.isSortingEnabled()
        self.IconTable.setSortingEnabled(False)
        item = self.IconTable.item(0, 1)
        item.setText(_translate("icon_configuration", "initial_state"))
        item = self.IconTable.item(0, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(0, 3)
        item.setText(_translate("icon_configuration", "🔴 "))
        item = self.IconTable.item(1, 1)
        item.setText(_translate("icon_configuration", "start_state"))
        item = self.IconTable.item(1, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(1, 3)
        item.setText(_translate("icon_configuration", "🔵"))
        item = self.IconTable.item(2, 1)
        item.setText(_translate("icon_configuration", "attack_state"))
        item = self.IconTable.item(2, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(2, 3)
        item.setText(_translate("icon_configuration", "🌀"))
        item = self.IconTable.item(3, 1)
        item.setText(_translate("icon_configuration", "verify_state"))
        item = self.IconTable.item(3, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(3, 3)
        item.setText(_translate("icon_configuration", "⭕"))
        item = self.IconTable.item(4, 1)
        item.setText(_translate("icon_configuration", "clear_state"))
        item = self.IconTable.item(4, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(4, 3)
        item.setText(_translate("icon_configuration", "💬"))
        item = self.IconTable.item(5, 1)
        item.setText(_translate("icon_configuration", "ready_state"))
        item = self.IconTable.item(5, 2)
        item.setText(_translate("icon_configuration", "emojipedia.org"))
        item = self.IconTable.item(5, 3)
        item.setText(_translate("icon_configuration", "✅"))
        self.IconTable.setSortingEnabled(__sortingEnabled)
