# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PICK(object):
    def setupUi(self, PICK):
        PICK.setObjectName("PICK")
        PICK.setWindowModality(QtCore.Qt.ApplicationModal)
        PICK.resize(1280, 655)
        PICK.setAutoFillBackground(True)
        PICK.setAnimated(True)
        PICK.setTabShape(QtWidgets.QTabWidget.Triangular)
        PICK.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(PICK)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tc_frame = QtWidgets.QFrame(self.tab)
        self.tc_frame.setMinimumSize(QtCore.QSize(610, 90))
        self.tc_frame.setMaximumSize(QtCore.QSize(610, 90))
        self.tc_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tc_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tc_frame.setObjectName("tc_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tc_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_tc = QtWidgets.QLabel(self.tc_frame)
        self.label_tc.setObjectName("label_tc")
        self.verticalLayout_2.addWidget(self.label_tc)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_lead = QtWidgets.QCheckBox(self.tc_frame)
        self.checkBox_lead.setObjectName("checkBox_lead")
        self.horizontalLayout_4.addWidget(self.checkBox_lead)
        self.label_ip_addr = QtWidgets.QLabel(self.tc_frame)
        self.label_ip_addr.setObjectName("label_ip_addr")
        self.horizontalLayout_4.addWidget(self.label_ip_addr)
        self.textbox_ip = QtWidgets.QPlainTextEdit(self.tc_frame)
        self.textbox_ip.setMaximumSize(QtCore.QSize(16777215, 28))
        self.textbox_ip.setObjectName("textbox_ip")
        self.horizontalLayout_4.addWidget(self.textbox_ip)
        self.button_connect_to_ip = QtWidgets.QPushButton(self.tc_frame)
        self.button_connect_to_ip.setMinimumSize(QtCore.QSize(100, 0))
        self.button_connect_to_ip.setObjectName("button_connect_to_ip")
        self.horizontalLayout_4.addWidget(self.button_connect_to_ip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_established_connections = QtWidgets.QLabel(self.tc_frame)
        self.label_established_connections.setObjectName("label_established_connections")
        self.horizontalLayout_9.addWidget(self.label_established_connections)
        self.label_number_established_connections = QtWidgets.QLabel(self.tc_frame)
        self.label_number_established_connections.setObjectName("label_number_established_connections")
        self.horizontalLayout_9.addWidget(self.label_number_established_connections)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_10.addWidget(self.tc_frame)
        self.vc_frame = QtWidgets.QFrame(self.tab)
        self.vc_frame.setMinimumSize(QtCore.QSize(600, 200))
        self.vc_frame.setMaximumSize(QtCore.QSize(610, 16777215))
        self.vc_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vc_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vc_frame.setObjectName("vc_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.vc_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.vc_label = QtWidgets.QLabel(self.vc_frame)
        self.vc_label.setMaximumSize(QtCore.QSize(16777215, 28))
        self.vc_label.setObjectName("vc_label")
        self.gridLayout_5.addWidget(self.vc_label, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.vc_table = QtWidgets.QTableWidget(self.vc_frame)
        self.vc_table.setObjectName("vc_table")
        self.vc_table.setColumnCount(3)
        self.vc_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vc_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_table.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_16.addWidget(self.vc_table)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.button__edit_vector = QtWidgets.QPushButton(self.vc_frame)
        self.button__edit_vector.setMinimumSize(QtCore.QSize(100, 0))
        self.button__edit_vector.setObjectName("button__edit_vector")
        self.verticalLayout_18.addWidget(self.button__edit_vector)
        self.button_add_vector = QtWidgets.QPushButton(self.vc_frame)
        self.button_add_vector.setObjectName("button_add_vector")
        self.verticalLayout_18.addWidget(self.button_add_vector)
        self.button_delete_vector = QtWidgets.QPushButton(self.vc_frame)
        self.button_delete_vector.setObjectName("button_delete_vector")
        self.verticalLayout_18.addWidget(self.button_delete_vector)
        self.vc_export_pushButton = QtWidgets.QPushButton(self.vc_frame)
        self.vc_export_pushButton.setObjectName("vc_export_pushButton")
        self.verticalLayout_18.addWidget(self.vc_export_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_18)
        self.gridLayout_5.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.vc_frame)
        self.horizontalLayout_8.addLayout(self.verticalLayout_10)
        self.lfc_frame = QtWidgets.QFrame(self.tab)
        self.lfc_frame.setMinimumSize(QtCore.QSize(600, 0))
        self.lfc_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lfc_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lfc_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lfc_frame.setObjectName("lfc_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.lfc_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.log_file_configuration_label = QtWidgets.QLabel(self.lfc_frame)
        self.log_file_configuration_label.setObjectName("log_file_configuration_label")
        self.verticalLayout_9.addWidget(self.log_file_configuration_label)
        self.frame = QtWidgets.QFrame(self.lfc_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_11.addWidget(self.tableWidget)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.log_file_export_pushButton = QtWidgets.QPushButton(self.frame_4)
        self.log_file_export_pushButton.setObjectName("log_file_export_pushButton")
        self.horizontalLayout_10.addWidget(self.log_file_export_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.frame_4)
        self.verticalLayout_9.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.lfc_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.gridLayout_4.addWidget(self.tableWidget_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ear_export_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.ear_export_pushButton.setObjectName("ear_export_pushButton")
        self.horizontalLayout_2.addWidget(self.ear_export_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(130, 0))
        self.pushButton_4.setTabletTracking(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem4)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.horizontalLayout_8.addWidget(self.lfc_frame)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.log_entry_tab = QtWidgets.QWidget()
        self.log_entry_tab.setObjectName("log_entry_tab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.log_entry_tab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fc_groupbox = QtWidgets.QGroupBox(self.log_entry_tab)
        self.fc_groupbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.fc_groupbox.setObjectName("fc_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fc_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fc_keyword_search_text = QtWidgets.QPlainTextEdit(self.fc_groupbox)
        self.fc_keyword_search_text.setMinimumSize(QtCore.QSize(0, 28))
        self.fc_keyword_search_text.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fc_keyword_search_text.setObjectName("fc_keyword_search_text")
        self.horizontalLayout_3.addWidget(self.fc_keyword_search_text)
        self.fc_starttimestamp_text = QtWidgets.QTextEdit(self.fc_groupbox)
        self.fc_starttimestamp_text.setMinimumSize(QtCore.QSize(100, 28))
        self.fc_starttimestamp_text.setMaximumSize(QtCore.QSize(100, 28))
        self.fc_starttimestamp_text.setObjectName("fc_starttimestamp_text")
        self.horizontalLayout_3.addWidget(self.fc_starttimestamp_text)
        self.fc_endtimestamp_text = QtWidgets.QTextEdit(self.fc_groupbox)
        self.fc_endtimestamp_text.setMinimumSize(QtCore.QSize(100, 28))
        self.fc_endtimestamp_text.setMaximumSize(QtCore.QSize(100, 28))
        self.fc_endtimestamp_text.setObjectName("fc_endtimestamp_text")
        self.horizontalLayout_3.addWidget(self.fc_endtimestamp_text)
        self.fc_applyfilter_button = QtWidgets.QPushButton(self.fc_groupbox)
        self.fc_applyfilter_button.setMinimumSize(QtCore.QSize(70, 24))
        self.fc_applyfilter_button.setMaximumSize(QtCore.QSize(70, 24))
        self.fc_applyfilter_button.setObjectName("fc_applyfilter_button")
        self.horizontalLayout_3.addWidget(self.fc_applyfilter_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fc_creator_label = QtWidgets.QLabel(self.fc_groupbox)
        self.fc_creator_label.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_creator_label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_creator_label.setObjectName("fc_creator_label")
        self.horizontalLayout.addWidget(self.fc_creator_label)
        self.fc_creatorred_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_creatorred_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_creatorred_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_creatorred_checkbox.setObjectName("fc_creatorred_checkbox")
        self.horizontalLayout.addWidget(self.fc_creatorred_checkbox)
        self.fc_creatorwhite_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_creatorwhite_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_creatorwhite_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_creatorwhite_checkbox.setObjectName("fc_creatorwhite_checkbox")
        self.horizontalLayout.addWidget(self.fc_creatorwhite_checkbox)
        self.fc_creatorblue_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_creatorblue_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_creatorblue_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_creatorblue_checkbox.setObjectName("fc_creatorblue_checkbox")
        self.horizontalLayout.addWidget(self.fc_creatorblue_checkbox)
        self.fc_eventtype_label = QtWidgets.QLabel(self.fc_groupbox)
        self.fc_eventtype_label.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_eventtype_label.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_eventtype_label.setObjectName("fc_eventtype_label")
        self.horizontalLayout.addWidget(self.fc_eventtype_label)
        self.fc_eventtyperede_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_eventtyperede_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_eventtyperede_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_eventtyperede_checkbox.setObjectName("fc_eventtyperede_checkbox")
        self.horizontalLayout.addWidget(self.fc_eventtyperede_checkbox)
        self.fc_eventtypewhite_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_eventtypewhite_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_eventtypewhite_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_eventtypewhite_checkbox.setObjectName("fc_eventtypewhite_checkbox")
        self.horizontalLayout.addWidget(self.fc_eventtypewhite_checkbox)
        self.fc_eventtypeblue_checkbox = QtWidgets.QCheckBox(self.fc_groupbox)
        self.fc_eventtypeblue_checkbox.setMinimumSize(QtCore.QSize(0, 24))
        self.fc_eventtypeblue_checkbox.setMaximumSize(QtCore.QSize(16777215, 24))
        self.fc_eventtypeblue_checkbox.setObjectName("fc_eventtypeblue_checkbox")
        self.horizontalLayout.addWidget(self.fc_eventtypeblue_checkbox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_6.addWidget(self.fc_groupbox)
        self.lec_groupbox = QtWidgets.QGroupBox(self.log_entry_tab)
        self.lec_groupbox.setMinimumSize(QtCore.QSize(600, 450))
        self.lec_groupbox.setObjectName("lec_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lec_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lec_logentry_table = QtWidgets.QTableWidget(self.lec_groupbox)
        self.lec_logentry_table.setMinimumSize(QtCore.QSize(550, 400))
        self.lec_logentry_table.setMaximumSize(QtCore.QSize(14243231, 16777215))
        self.lec_logentry_table.setObjectName("lec_logentry_table")
        self.lec_logentry_table.setColumnCount(5)
        self.lec_logentry_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lec_logentry_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lec_logentry_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lec_logentry_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lec_logentry_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lec_logentry_table.setHorizontalHeaderItem(4, item)
        self.lec_logentry_table.horizontalHeader().setDefaultSectionSize(120)
        self.lec_logentry_table.verticalHeader().setMinimumSectionSize(32)
        self.verticalLayout.addWidget(self.lec_logentry_table)
        self.verticalLayout_6.addWidget(self.lec_groupbox)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ec_groupbox = QtWidgets.QGroupBox(self.log_entry_tab)
        self.ec_groupbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ec_groupbox.setObjectName("ec_groupbox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ec_groupbox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ec_formattype_combobox = QtWidgets.QComboBox(self.ec_groupbox)
        self.ec_formattype_combobox.setMinimumSize(QtCore.QSize(40, 24))
        self.ec_formattype_combobox.setMaximumSize(QtCore.QSize(60, 24))
        self.ec_formattype_combobox.setObjectName("ec_formattype_combobox")
        self.ec_formattype_combobox.addItem("")
        self.ec_formattype_combobox.addItem("")
        self.ec_formattype_combobox.addItem("")
        self.ec_formattype_combobox.addItem("")
        self.horizontalLayout_5.addWidget(self.ec_formattype_combobox)
        self.ec_export_button = QtWidgets.QPushButton(self.ec_groupbox)
        self.ec_export_button.setMinimumSize(QtCore.QSize(60, 24))
        self.ec_export_button.setMaximumSize(QtCore.QSize(60, 24))
        self.ec_export_button.setObjectName("ec_export_button")
        self.horizontalLayout_5.addWidget(self.ec_export_button)
        self.verticalLayout_5.addWidget(self.ec_groupbox)
        self.cc_groupbox = QtWidgets.QGroupBox(self.log_entry_tab)
        self.cc_groupbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cc_groupbox.setObjectName("cc_groupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.cc_groupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ec_changelist_button = QtWidgets.QLabel(self.cc_groupbox)
        self.ec_changelist_button.setMinimumSize(QtCore.QSize(0, 20))
        self.ec_changelist_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ec_changelist_button.setObjectName("ec_changelist_button")
        self.verticalLayout_4.addWidget(self.ec_changelist_button)
        self.ec_changelist_list = QtWidgets.QListWidget(self.cc_groupbox)
        self.ec_changelist_list.setMinimumSize(QtCore.QSize(130, 150))
        self.ec_changelist_list.setMaximumSize(QtCore.QSize(130, 150))
        self.ec_changelist_list.setObjectName("ec_changelist_list")
        self.verticalLayout_4.addWidget(self.ec_changelist_list)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ec_undo_button = QtWidgets.QPushButton(self.cc_groupbox)
        self.ec_undo_button.setMinimumSize(QtCore.QSize(50, 24))
        self.ec_undo_button.setMaximumSize(QtCore.QSize(50, 24))
        self.ec_undo_button.setObjectName("ec_undo_button")
        self.horizontalLayout_6.addWidget(self.ec_undo_button)
        self.ec_commit_button = QtWidgets.QPushButton(self.cc_groupbox)
        self.ec_commit_button.setMinimumSize(QtCore.QSize(65, 24))
        self.ec_commit_button.setMaximumSize(QtCore.QSize(65, 24))
        self.ec_commit_button.setObjectName("ec_commit_button")
        self.horizontalLayout_6.addWidget(self.ec_commit_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.cc_groupbox)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.log_entry_tab, "")
        self.vc_tab = QtWidgets.QWidget()
        self.vc_tab.setObjectName("vc_tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.vc_tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vc_verticalLayout = QtWidgets.QVBoxLayout()
        self.vc_verticalLayout.setObjectName("vc_verticalLayout")
        self.vc_toolbar_layout = QtWidgets.QHBoxLayout()
        self.vc_toolbar_layout.setObjectName("vc_toolbar_layout")
        self.vc_vector_drop_down = QtWidgets.QComboBox(self.vc_tab)
        self.vc_vector_drop_down.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_vector_drop_down.setFont(font)
        self.vc_vector_drop_down.setEditable(True)
        self.vc_vector_drop_down.setIconSize(QtCore.QSize(10, 10))
        self.vc_vector_drop_down.setObjectName("vc_vector_drop_down")
        self.vc_toolbar_layout.addWidget(self.vc_vector_drop_down)
        self.vc_undo_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_undo_button.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_undo_button.setFont(font)
        self.vc_undo_button.setObjectName("vc_undo_button")
        self.vc_toolbar_layout.addWidget(self.vc_undo_button)
        self.vc_redo_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_redo_button.setMinimumSize(QtCore.QSize(40, 0))
        self.vc_redo_button.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_redo_button.setFont(font)
        self.vc_redo_button.setObjectName("vc_redo_button")
        self.vc_toolbar_layout.addWidget(self.vc_redo_button)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.vc_toolbar_layout.addItem(spacerItem7)
        self.vc_add_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_add_button.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_add_button.setFont(font)
        self.vc_add_button.setObjectName("vc_add_button")
        self.vc_toolbar_layout.addWidget(self.vc_add_button)
        self.vc_delete_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_delete_button.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_delete_button.setFont(font)
        self.vc_delete_button.setIconSize(QtCore.QSize(10, 24))
        self.vc_delete_button.setObjectName("vc_delete_button")
        self.vc_toolbar_layout.addWidget(self.vc_delete_button)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.vc_toolbar_layout.addItem(spacerItem8)
        self.vc_push_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_push_button.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_push_button.setFont(font)
        self.vc_push_button.setObjectName("vc_push_button")
        self.vc_toolbar_layout.addWidget(self.vc_push_button)
        self.vc_verticalLayout.addLayout(self.vc_toolbar_layout)
        self.vc_searchbar_layout = QtWidgets.QHBoxLayout()
        self.vc_searchbar_layout.setObjectName("vc_searchbar_layout")
        self.vc_search_box = QtWidgets.QPlainTextEdit(self.vc_tab)
        self.vc_search_box.setMinimumSize(QtCore.QSize(20, 0))
        self.vc_search_box.setMaximumSize(QtCore.QSize(250, 30))
        self.vc_search_box.setObjectName("vc_search_box")
        self.vc_searchbar_layout.addWidget(self.vc_search_box)
        self.vc_keyword_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_keyword_button.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_keyword_button.setFont(font)
        self.vc_keyword_button.setObjectName("vc_keyword_button")
        self.vc_searchbar_layout.addWidget(self.vc_keyword_button)
        self.vc_filter_dropdown = QtWidgets.QComboBox(self.vc_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_filter_dropdown.setFont(font)
        self.vc_filter_dropdown.setObjectName("vc_filter_dropdown")
        self.vc_filter_dropdown.addItem("")
        self.vc_searchbar_layout.addWidget(self.vc_filter_dropdown)
        self.vc_verticalLayout.addLayout(self.vc_searchbar_layout)
        self.vc_node_table = QtWidgets.QTableWidget(self.vc_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_node_table.setFont(font)
        self.vc_node_table.setObjectName("vc_node_table")
        self.vc_node_table.setColumnCount(10)
        self.vc_node_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_node_table.setHorizontalHeaderItem(9, item)
        self.vc_node_table.horizontalHeader().setDefaultSectionSize(80)
        self.vc_verticalLayout.addWidget(self.vc_node_table)
        self.horizontalLayout_12.addLayout(self.vc_verticalLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.vc_graph_view = QtWidgets.QGraphicsView(self.vc_tab)
        self.vc_graph_view.setObjectName("vc_graph_view")
        self.verticalLayout_8.addWidget(self.vc_graph_view)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.nc_interval_textedit = QtWidgets.QPlainTextEdit(self.vc_tab)
        self.nc_interval_textedit.setMaximumSize(QtCore.QSize(150, 25))
        self.nc_interval_textedit.setObjectName("nc_interval_textedit")
        self.horizontalLayout_11.addWidget(self.nc_interval_textedit)
        self.nc_units_dropdown = QtWidgets.QComboBox(self.vc_tab)
        self.nc_units_dropdown.setMaximumSize(QtCore.QSize(80, 25))
        self.nc_units_dropdown.setObjectName("nc_units_dropdown")
        self.nc_units_dropdown.addItem("")
        self.horizontalLayout_11.addWidget(self.nc_units_dropdown)
        self.nc_zoomin_button_2 = QtWidgets.QPushButton(self.vc_tab)
        self.nc_zoomin_button_2.setMaximumSize(QtCore.QSize(65, 25))
        self.nc_zoomin_button_2.setObjectName("nc_zoomin_button_2")
        self.horizontalLayout_11.addWidget(self.nc_zoomin_button_2)
        self.nc_zoomin_button = QtWidgets.QPushButton(self.vc_tab)
        self.nc_zoomin_button.setMaximumSize(QtCore.QSize(65, 25))
        self.nc_zoomin_button.setObjectName("nc_zoomin_button")
        self.horizontalLayout_11.addWidget(self.nc_zoomin_button)
        self.nc_iconchange_button = QtWidgets.QPushButton(self.vc_tab)
        self.nc_iconchange_button.setMaximumSize(QtCore.QSize(85, 25))
        self.nc_iconchange_button.setObjectName("nc_iconchange_button")
        self.horizontalLayout_11.addWidget(self.nc_iconchange_button)
        spacerItem9 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.nc_export_dropdown = QtWidgets.QComboBox(self.vc_tab)
        self.nc_export_dropdown.setMaximumSize(QtCore.QSize(55, 25))
        self.nc_export_dropdown.setObjectName("nc_export_dropdown")
        self.nc_export_dropdown.addItem("")
        self.nc_export_dropdown.addItem("")
        self.nc_export_dropdown.addItem("")
        self.horizontalLayout_11.addWidget(self.nc_export_dropdown)
        self.nc_export_button = QtWidgets.QPushButton(self.vc_tab)
        self.nc_export_button.setMinimumSize(QtCore.QSize(0, 25))
        self.nc_export_button.setMaximumSize(QtCore.QSize(45, 25))
        self.nc_export_button.setObjectName("nc_export_button")
        self.horizontalLayout_11.addWidget(self.nc_export_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.vc_relationship_table = QtWidgets.QTableWidget(self.vc_tab)
        self.vc_relationship_table.setMaximumSize(QtCore.QSize(16777215, 235))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vc_relationship_table.setFont(font)
        self.vc_relationship_table.setObjectName("vc_relationship_table")
        self.vc_relationship_table.setColumnCount(4)
        self.vc_relationship_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.vc_relationship_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_relationship_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_relationship_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.vc_relationship_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout_8.addWidget(self.vc_relationship_table)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem10)
        self.vc_add_relationship_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_add_relationship_button.setMinimumSize(QtCore.QSize(98, 0))
        self.vc_add_relationship_button.setObjectName("vc_add_relationship_button")
        self.horizontalLayout_19.addWidget(self.vc_add_relationship_button)
        self.vc_rm_relationship_button = QtWidgets.QPushButton(self.vc_tab)
        self.vc_rm_relationship_button.setMinimumSize(QtCore.QSize(118, 0))
        self.vc_rm_relationship_button.setObjectName("vc_rm_relationship_button")
        self.horizontalLayout_19.addWidget(self.vc_rm_relationship_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.vc_tab, "")
        self.horizontalLayout_20.addWidget(self.tabWidget)
        PICK.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(PICK)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 20))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSPLUNK = QtWidgets.QMenu(self.menuBar)
        self.menuSPLUNK.setObjectName("menuSPLUNK")
        PICK.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(PICK)
        self.actionNew.setStatusTip("")
        self.actionNew.setWhatsThis("")
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(PICK)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(PICK)
        self.actionExit.setObjectName("actionExit")
        self.actionEdit = QtWidgets.QAction(PICK)
        self.actionEdit.setObjectName("actionEdit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSPLUNK.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PICK)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(PICK)

    def retranslateUi(self, PICK):
        _translate = QtCore.QCoreApplication.translate
        PICK.setWindowTitle(_translate("PICK", "PMR Insight Collective Knowledge"))
        self.label_tc.setText(_translate("PICK", "Team Configuration"))
        self.checkBox_lead.setText(_translate("PICK", "Lead"))
        self.label_ip_addr.setText(_translate("PICK", "|  Lead IP Address:"))
        self.button_connect_to_ip.setText(_translate("PICK", "Connect"))
        self.label_established_connections.setText(_translate("PICK", "No. of established connections to the lead’s IP address:"))
        self.label_number_established_connections.setText(_translate("PICK", "0"))
        self.vc_label.setText(_translate("PICK", "Vector Configuration"))
        item = self.vc_table.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "Vector Name"))
        item = self.vc_table.horizontalHeaderItem(2)
        item.setText(_translate("PICK", "Vector Description"))
        self.button__edit_vector.setText(_translate("PICK", "Edit"))
        self.button_add_vector.setText(_translate("PICK", "Add"))
        self.button_delete_vector.setText(_translate("PICK", "Delete"))
        self.vc_export_pushButton.setText(_translate("PICK", "Export Table"))
        self.log_file_configuration_label.setText(_translate("PICK", "Log File Configuration"))
        self.label_2.setText(_translate("PICK", "Log File Table:    "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PICK", "File Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "Source"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("PICK", "Cleansing Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("PICK", "Validation Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("PICK", "Ingestion Status"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("PICK", "View Report"))
        self.log_file_export_pushButton.setText(_translate("PICK", "Export"))
        self.label_5.setText(_translate("PICK", "Enforcement Action Report"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("PICK", "Line Number"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "Error Message"))
        self.ear_export_pushButton.setText(_translate("PICK", "Export"))
        self.pushButton_3.setText(_translate("PICK", "Validate"))
        self.pushButton_4.setText(_translate("PICK", "Cancel"))
        self.label_11.setText(_translate("PICK", "File Name:"))
        self.label_12.setText(_translate("PICK", "File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PICK", "Event"))
        self.fc_groupbox.setTitle(_translate("PICK", "Filter Configuration"))
        self.fc_keyword_search_text.setPlainText(_translate("PICK", "Keyword Search"))
        self.fc_starttimestamp_text.setHtml(_translate("PICK", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">Start Timestamp</span></p></body></html>"))
        self.fc_endtimestamp_text.setHtml(_translate("PICK", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">End Timestamp</span></p></body></html>"))
        self.fc_applyfilter_button.setText(_translate("PICK", "Apply Filter"))
        self.fc_creator_label.setText(_translate("PICK", "Creator:"))
        self.fc_creatorred_checkbox.setText(_translate("PICK", "Red"))
        self.fc_creatorwhite_checkbox.setText(_translate("PICK", "White"))
        self.fc_creatorblue_checkbox.setText(_translate("PICK", "Blue"))
        self.fc_eventtype_label.setText(_translate("PICK", "  ||    Event Type:"))
        self.fc_eventtyperede_checkbox.setText(_translate("PICK", "Red"))
        self.fc_eventtypewhite_checkbox.setText(_translate("PICK", "White"))
        self.fc_eventtypeblue_checkbox.setText(_translate("PICK", "Blue"))
        self.lec_groupbox.setTitle(_translate("PICK", "Log Entry Configuration"))
        item = self.lec_logentry_table.horizontalHeaderItem(0)
        item.setText(_translate("PICK", "Select"))
        item = self.lec_logentry_table.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "▲ List Number"))
        item = self.lec_logentry_table.horizontalHeaderItem(2)
        item.setText(_translate("PICK", "▲ Timestamp"))
        item = self.lec_logentry_table.horizontalHeaderItem(3)
        item.setText(_translate("PICK", "▲ Log Entry Event"))
        item = self.lec_logentry_table.horizontalHeaderItem(4)
        item.setText(_translate("PICK", "▲ Vector"))
        self.ec_groupbox.setTitle(_translate("PICK", "Export Configuration"))
        self.ec_formattype_combobox.setItemText(0, _translate("PICK", "CSV"))
        self.ec_formattype_combobox.setItemText(1, _translate("PICK", "PDF"))
        self.ec_formattype_combobox.setItemText(2, _translate("PICK", "JPG"))
        self.ec_formattype_combobox.setItemText(3, _translate("PICK", "PNG"))
        self.ec_export_button.setText(_translate("PICK", "Export"))
        self.cc_groupbox.setTitle(_translate("PICK", "Change Configuration"))
        self.ec_changelist_button.setText(_translate("PICK", "Change List"))
        self.ec_undo_button.setText(_translate("PICK", "Undo"))
        self.ec_commit_button.setText(_translate("PICK", "Commit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_entry_tab), _translate("PICK", "Log View"))
        self.vc_vector_drop_down.setCurrentText(_translate("PICK", "Vector"))
        self.vc_undo_button.setText(_translate("PICK", "Undo"))
        self.vc_redo_button.setText(_translate("PICK", "Redo"))
        self.vc_add_button.setText(_translate("PICK", "Add"))
        self.vc_delete_button.setText(_translate("PICK", "Delete"))
        self.vc_push_button.setText(_translate("PICK", "VC"))
        self.vc_search_box.setPlainText(_translate("PICK", "Keyword"))
        self.vc_keyword_button.setText(_translate("PICK", "Keyword Filter"))
        self.vc_filter_dropdown.setCurrentText(_translate("PICK", "Filter by Attribute"))
        self.vc_filter_dropdown.setItemText(0, _translate("PICK", "Filter by Attribute"))
        item = self.vc_node_table.horizontalHeaderItem(0)
        item.setText(_translate("PICK", "NodeID"))
        item = self.vc_node_table.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "Name"))
        item = self.vc_node_table.horizontalHeaderItem(2)
        item.setText(_translate("PICK", "Date/Time"))
        item = self.vc_node_table.horizontalHeaderItem(3)
        item.setText(_translate("PICK", "Description"))
        item = self.vc_node_table.horizontalHeaderItem(4)
        item.setText(_translate("PICK", "Reference"))
        item = self.vc_node_table.horizontalHeaderItem(5)
        item.setText(_translate("PICK", "Creator"))
        item = self.vc_node_table.horizontalHeaderItem(6)
        item.setText(_translate("PICK", "Event Type"))
        item = self.vc_node_table.horizontalHeaderItem(7)
        item.setText(_translate("PICK", "Icon Type"))
        item = self.vc_node_table.horizontalHeaderItem(8)
        item.setText(_translate("PICK", "Artifact"))
        item = self.vc_node_table.horizontalHeaderItem(9)
        item.setText(_translate("PICK", "Visibility"))
        self.nc_interval_textedit.setPlainText(_translate("PICK", "Interval"))
        self.nc_units_dropdown.setCurrentText(_translate("PICK", "Units"))
        self.nc_units_dropdown.setItemText(0, _translate("PICK", "Units"))
        self.nc_zoomin_button_2.setText(_translate("PICK", "Zoom In"))
        self.nc_zoomin_button.setText(_translate("PICK", "Zoom Out"))
        self.nc_iconchange_button.setText(_translate("PICK", "Change Icon"))
        self.nc_export_dropdown.setItemText(0, _translate("PICK", "CSV"))
        self.nc_export_dropdown.setItemText(1, _translate("PICK", "PNG"))
        self.nc_export_dropdown.setItemText(2, _translate("PICK", "JPG"))
        self.nc_export_button.setText(_translate("PICK", "Export"))
        item = self.vc_relationship_table.horizontalHeaderItem(0)
        item.setText(_translate("PICK", "Relationship ID"))
        item = self.vc_relationship_table.horizontalHeaderItem(1)
        item.setText(_translate("PICK", "Label"))
        item = self.vc_relationship_table.horizontalHeaderItem(2)
        item.setText(_translate("PICK", "Parent ID"))
        item = self.vc_relationship_table.horizontalHeaderItem(3)
        item.setText(_translate("PICK", "Child ID"))
        self.vc_add_relationship_button.setText(_translate("PICK", "Add Relationship"))
        self.vc_rm_relationship_button.setText(_translate("PICK", "Remove Relationship"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vc_tab), _translate("PICK", "Vector View"))
        self.menuFile.setTitle(_translate("PICK", "File"))
        self.menuHelp.setTitle(_translate("PICK", "Help"))
        self.menuSPLUNK.setTitle(_translate("PICK", "SPLUNK"))
        self.actionNew.setText(_translate("PICK", "New"))
        self.actionNew.setShortcut(_translate("PICK", "Ctrl+N"))
        self.actionOpen.setText(_translate("PICK", "Open.."))
        self.actionOpen.setShortcut(_translate("PICK", "Ctrl+O"))
        self.actionExit.setText(_translate("PICK", "Exit"))
        self.actionExit.setShortcut(_translate("PICK", "Ctrl+E"))
        self.actionEdit.setText(_translate("PICK", "Edit Event"))

